using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Text.Json;
using System.Text.RegularExpressions;

namespace SpreadsheetApp.Core
{
    public sealed class DocsIndex
    {
        public DateTime GeneratedAt { get; set; } = DateTime.UtcNow;
        public List<DocFile> Files { get; set; } = new();
    }

    public sealed class DocFile
    {
        public string Name { get; set; } = string.Empty;
        public string Path { get; set; } = string.Empty;
        public string? Title { get; set; }
        public List<DocSection> Sections { get; set; } = new();
        public string Content { get; set; } = string.Empty;
    }

    public sealed class DocSection
    {
        public int Level { get; set; }
        public string Title { get; set; } = string.Empty;
        public string Content { get; set; } = string.Empty;
    }

    public static class DocsIndexer
    {
        // Files to include by default at repository root
        private static readonly string[] DefaultDocGlobs = new[]
        {
            "*.md"
        };

        private static bool IsIgnored(string fileName)
        {
            // Ignore common non-doc or autogenerated md files here if needed
            var bn = System.IO.Path.GetFileName(fileName);
            if (string.Equals(bn, "README.md", StringComparison.OrdinalIgnoreCase)) return false;
            return false;
        }

        public static string? TryFindRepoRoot()
        {
            // Walk up from app base directory looking for the .csproj at repo root
            string start = AppDomain.CurrentDomain.BaseDirectory;
            var dir = new DirectoryInfo(start);
            for (int i = 0; i < 8 && dir != null; i++)
            {
                var csproj = dir.GetFiles("*.csproj", SearchOption.TopDirectoryOnly).FirstOrDefault();
                if (csproj != null)
                {
                    // Likely the project root
                    return dir.FullName;
                }
                dir = dir.Parent;
            }
            return null;
        }

        public static DocsIndex Build(string? root = null, IEnumerable<string>? includeGlobs = null)
        {
            root ??= TryFindRepoRoot() ?? Environment.CurrentDirectory;
            var idx = new DocsIndex { GeneratedAt = DateTime.UtcNow };
            if (!Directory.Exists(root)) return idx;

            var globs = (includeGlobs != null && includeGlobs.Any()) ? includeGlobs.ToArray() : DefaultDocGlobs;
            var files = new List<string>();
            foreach (var g in globs)
            {
                try
                {
                    files.AddRange(Directory.GetFiles(root, g, SearchOption.TopDirectoryOnly));
                }
                catch { }
            }

            // Filter basic noisy files if desired
            files = files.Where(f => !IsIgnored(f)).OrderBy(f => Path.GetFileName(f), StringComparer.OrdinalIgnoreCase).ToList();

            foreach (var path in files)
            {
                try
                {
                    string text = File.ReadAllText(path);
                    var doc = new DocFile
                    {
                        Name = System.IO.Path.GetFileName(path),
                        Path = MakeRelativePath(root, path),
                        Content = text
                    };
                    ParseSections(text, doc);
                    idx.Files.Add(doc);
                }
                catch { }
            }

            return idx;
        }

        public static string WriteJson(DocsIndex index, string? outputPath = null)
        {
            string root = TryFindRepoRoot() ?? Environment.CurrentDirectory;
            string outDir = outputPath == null ? System.IO.Path.Combine(root, "docs") : System.IO.Path.GetDirectoryName(outputPath)!;
            string outFile = outputPath == null ? System.IO.Path.Combine(outDir, "docs_index.json") : outputPath;
            try
            {
                if (!Directory.Exists(outDir)) Directory.CreateDirectory(outDir);
            }
            catch { }

            var opts = new JsonSerializerOptions
            {
                WriteIndented = true
            };
            string json = JsonSerializer.Serialize(index, opts);
            try { File.WriteAllText(outFile, json); } catch { }
            return outFile;
        }

        private static void ParseSections(string text, DocFile doc)
        {
            var lines = text.Split(new[] { "\r\n", "\n" }, StringSplitOptions.None);
            var headerRx = new Regex("^(#{1,6})\\s+(.*)$");
            DocSection? current = null;
            int firstH1Index = -1;
            for (int i = 0; i < lines.Length; i++)
            {
                var line = lines[i];
                var m = headerRx.Match(line);
                if (m.Success)
                {
                    // Finish previous section
                    if (current != null)
                    {
                        doc.Sections.Add(current);
                    }
                    int level = m.Groups[1].Value.Length;
                    string title = m.Groups[2].Value.Trim();
                    current = new DocSection { Level = level, Title = title, Content = string.Empty };
                    if (level == 1 && firstH1Index < 0)
                    {
                        firstH1Index = doc.Sections.Count; // index where this would be after add
                        doc.Title = title;
                    }
                }
                else
                {
                    if (current == null)
                    {
                        // Preamble before first header becomes an implicit section
                        current = new DocSection { Level = 1, Title = "Preamble", Content = string.Empty };
                    }
                    current.Content += (current.Content.Length == 0 ? string.Empty : "\n") + line;
                }
            }
            if (current != null) doc.Sections.Add(current);
            if (string.IsNullOrWhiteSpace(doc.Title))
            {
                // default title is filename without extension
                doc.Title = System.IO.Path.GetFileNameWithoutExtension(doc.Name);
            }
        }

        private static string MakeRelativePath(string root, string fullPath)
        {
            try
            {
                var rootUri = new Uri(AppendDirectorySeparatorChar(root));
                var fullUri = new Uri(fullPath);
                return Uri.UnescapeDataString(rootUri.MakeRelativeUri(fullUri).ToString().Replace('/', Path.DirectorySeparatorChar));
            }
            catch
            {
                return fullPath;
            }
        }

        private static string AppendDirectorySeparatorChar(string path)
        {
            if (!path.EndsWith(Path.DirectorySeparatorChar.ToString()))
            {
                return path + Path.DirectorySeparatorChar;
            }
            return path;
        }
    }
}

